project:
  type: website
  output-dir: docs
  resources:
    - "some_slides/"

website:
  title: "Journal Assignment: Cognitive Reappraisal"
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/
      - moi_slides.qmd
  
      
format:
  html:
    theme: minty
    css: styles.css

editor: visual

