project:
  type: website
  output-dir: docs

website:
  title: "Journal Assignment: Cognitive Reappraisal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      
format:
  html:
    theme: minty
    css: styles.css

editor: visual

